server:
  port: 9092

spring:
    data:
    mongodb:
      uri: mongodb://localhost:27017/hotelservice_db
      # Alternative configuration
      # host: localhost
      # port: 27017
      # database: hotelservice_db
      # username: root
      # password: password


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true    
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
