server:
  port: 9093   # Change per service

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update   # dev: update | prod: validate / none

    show-sql: true       # prints SQL in console

    properties:
      hibernate:
        format_sql: true     # pretty print SQL
        use_sql_comments: true  # adds comments to SQL
        jdbc:
          batch_size: 20     # batch inserts/updates
        order_inserts: true
        order_updates: true
        generate_statistics: false

  sql:
    init:
      mode: never   # prevents Spring from auto-running schema.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
